[package]
name = "todo_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.44.0", features = ["full"] }
